### ISSUE TITLE
keep track of contributing grid boxes

### ISSUE THREAD

**Issue by kmuehlbauer** [antarcticrainforest/tintX#33]
I'm wondering if it would be possible to somehow keep track of the lat/lon coords of each contributing grid box.

**Comment by antarcticrainforest** [comment]
Thanks @kmuehlbauer. Just to be sure that I am understanding the issue, could you specify what you mean by *contributing grid box*?  The code does store the coordinates of the storm centres:
|             | time                |   grid_x |   grid_y |     lon |      lat |   area |       max |      mean | isolated   |
|:------------|:--------------------|---------:|---------:|--------:|---------:|-------:|----------:|----------:|:-----------|
| (3, '19')   | 2006-11-16 03:30:00 |   88.441 |   53.088 | 131.735 | -12.3607 |     34 |  9.04645  |  1.59762  | True       |
| (3, '20')   | 2006-11-16 03:30:00 |   94.4   |   54.8   | 131.873 | -12.3154 |      5 |  0.128254 |  0.115688 | True       |
| (3, '21')   | 2006-11-16 03:30:00 |   36.034 |   83.794 | 130.539 | -11.6642 |    175 | 36.749    |  7.44233  | True       |

Am I missing something?

**Comment by kmuehlbauer** [comment]
@antarcticrainforest I'm interested in all grid-boxes (x/y coords) which contribute to that storm, not only the storm center coordinates. 

I'm trying to enhance statistics by going back into the 3D-data. If I knew the contributing grid boxes I would be able to grab the contributing data from the 3D array. Does that make sense?

**Comment by kmuehlbauer** [comment]
I've tinkered a bit with kind of uid-mask as this is an easy way to keep that information, but do not have a prototype yet.

I've also thought on minimizing that by adding something like a vector geometry (JSON Polygon or the like) to the dataframe (geopandas-like). This would be really nice for visualization. Could then just use any point-in-polygon approach to identify the wanted 3D grid points.

**Comment by antarcticrainforest** [comment]
Yes, I think that would work very well. Do you want to give it a shot or would like me to propose something?

**Comment by kmuehlbauer** [comment]
I can try to work something out. I might need some guidance, though. 

Does tintX have any constraints with regard to dependencies? We'd need to use some library to extract the shape features from the raster frames (eg. rasterio). Also geopandas might be needed.

I'll try to make this optional on user request.

**Comment by antarcticrainforest** [comment]
I'd say the only constraints are dependencies available via conda forge. Other than that, not really. Of course the less the better, but since we are already having xarray as a dependency, which brings a whole bunch of other packages, it doesn't really matter.
