### ISSUE TITLE
Polygons sometimes inverted

### ISSUE THREAD

**Issue by robinco1919** [antarcticrainforest/tintX#79]
Hi,

Firstly I'd like to thank the team for producing such an amazing package!

I'm having an issue where the polygons defining the area of the object are sometimes inverted. That is, the area where the condition is _not_ satisfied is marked, while everything else stays correct (e.g. the position and boundaries of the object).

See an example below, where I've created a moving Gaussian for the algorithm to detect (hopefully the animation is viewable!). In the last few frames you can see the inversion occur -- it seems to be when the object moves onto the boundary of the domain. (I can also send through the notebook I used to create this, but it seems Github doesn't like .ipynb files.)

https://github.com/antarcticrainforest/tintX/assets/65580851/b9a7a6f3-e8c9-433c-843b-d954517e9306

Thanks for any help!

**Comment by antarcticrainforest** [comment]
Hi @robinco1919, sorry for the late response. I was travelling for the last two months and have just gotten back.

That's indeed an interesting thing. 

Just so we are on the same page: you're referring to the change between 2020-01-04T20:00 and 2020-01-04T21:00?

It seems to me that for some reason the boundary of the field interferes with the polygon calculation. @kmuehlbauer any ideas? 

Anyways the notebook that creates this nice little moving blob would be great.

**Comment by robinco1919** [comment]
Thanks @antarcticrainforest, and hope you enjoyed your time away!

That's right - it's the change from 2020-01-04T20:00 to 2020-01-04T21:00 that's the problem. 

[Here's](https://github.com/robinco1919/phd_analysis_public/blob/main/tintx_inverted_issue.ipynb) the notebook used to create that animation.

**Comment by kmuehlbauer** [comment]
@robinco1919 Nice example notebook! I can think of three points of failure here, where failure is the wrong term anyway.

Here is the code to create the polygons:

https://github.com/antarcticrainforest/tintX/blob/a92d5c927293e0831cdc81323526335ce6acf3dd/src/tintx/objects.py#L263-L273

The inner part `features.shapes` is from `rasterio` which creates the actual polygon via [GDALPolygonize](https://gdal.org/api/gdal_alg.html#_CPPv414GDALPolygonize15GDALRasterBandH15GDALRasterBandH9OGRLayerHiPPc16GDALProgressFuncPv). The outer part is taken from `shapely` which imports it into a shapely geometry.

I do not think that this is an issue with `rasterio`/`GDAL` or `shapely` (we should check nevertheless). So we might have the problem already in `(image1 == obj).astype("uint16")` getting a reversed mask. That would probably the location where I would check first.

**Comment by robinco1919** [comment]
I'm very much out of my league with packages like rasterio, GDAL and shapely, but some quick testing on my end shows sensible outputs for `(image1 == obj).astype("uint16")`. That is, it's a 2D array with 1s in the (correct) object area, and 0s outside - even in the cases where we get a reversed mask in the final output.

So my guess is that it's something in the outer parts of the above snippet, though I don't think I can work it out myself!

**Comment by kmuehlbauer** [comment]
Thanks @robinco1919 for checking this. Then we will need to check the remaining parts. I can have a look into this.

**Comment by kmuehlbauer** [comment]
My bad, the assumption that the two shapes which are returned by `rasterio.features.shapes` are in the same order in any case is wrong. We need to iterate over the shapes and pick the one with the correct id.

@robinco1919 Could you check the below code in your installation. This should work in any case then. At least here this extracts the correct shapes. I'll prepare a PR later.

```python
            # iterate over shapes (we have only two) until
            # we have the correct one (with num == 1)
            # see https://github.com/antarcticrainforest/tintX/issues/79
            def get_shape(shapes):
                shp, sid = next(shapes)
                while not sid:
                    shp, sid = next(shapes)
                return geometry.shape(shp)

            # use safe dtype (uint16) in case of num_cells > 255
            poly.append(
                get_shape(
                    features.shapes(
                        (image1 == obj).astype("uint16"), transform=fwd
                    )
                )
            )

```

**Comment by robinco1919** [comment]
@kmuehlbauer I've tested it and it works perfectly on my end, both for the synthetic data and real data. Thank you very much!
